// This file is auto-generated by @hey-api/openapi-ts

export const AddressCreateSchema = {
    properties: {
        receiver_name: {
            type: 'string',
            maxLength: 255,
            title: 'Receiver Name'
        },
        receiver_phone: {
            type: 'string',
            maxLength: 32,
            title: 'Receiver Phone'
        },
        province: {
            type: 'string',
            maxLength: 100,
            title: 'Province'
        },
        city: {
            type: 'string',
            maxLength: 100,
            title: 'City'
        },
        district: {
            type: 'string',
            maxLength: 100,
            title: 'District'
        },
        detail: {
            type: 'string',
            maxLength: 255,
            title: 'Detail'
        },
        is_default: {
            type: 'boolean',
            title: 'Is Default',
            default: false
        }
    },
    type: 'object',
    required: ['receiver_name', 'receiver_phone', 'province', 'city', 'district', 'detail'],
    title: 'AddressCreate'
} as const;

export const AddressOverviewSchema = {
    properties: {
        total: {
            type: 'integer',
            title: 'Total'
        },
        default_count: {
            type: 'integer',
            title: 'Default Count'
        }
    },
    type: 'object',
    required: ['total', 'default_count'],
    title: 'AddressOverview'
} as const;

export const AddressPublicSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        user_id: {
            type: 'string',
            format: 'uuid',
            title: 'User Id'
        },
        receiver_name: {
            type: 'string',
            title: 'Receiver Name'
        },
        receiver_phone: {
            type: 'string',
            title: 'Receiver Phone'
        },
        province: {
            type: 'string',
            title: 'Province'
        },
        city: {
            type: 'string',
            title: 'City'
        },
        district: {
            type: 'string',
            title: 'District'
        },
        detail: {
            type: 'string',
            title: 'Detail'
        },
        is_default: {
            type: 'boolean',
            title: 'Is Default'
        },
        created_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Created At'
        }
    },
    type: 'object',
    required: ['id', 'user_id', 'receiver_name', 'receiver_phone', 'province', 'city', 'district', 'detail', 'is_default'],
    title: 'AddressPublic'
} as const;

export const AddressUpdateSchema = {
    properties: {
        receiver_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Receiver Name'
        },
        receiver_phone: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 32
                },
                {
                    type: 'null'
                }
            ],
            title: 'Receiver Phone'
        },
        province: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 100
                },
                {
                    type: 'null'
                }
            ],
            title: 'Province'
        },
        city: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 100
                },
                {
                    type: 'null'
                }
            ],
            title: 'City'
        },
        district: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 100
                },
                {
                    type: 'null'
                }
            ],
            title: 'District'
        },
        detail: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Detail'
        },
        is_default: {
            anyOf: [
                {
                    type: 'boolean'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Is Default'
        }
    },
    type: 'object',
    title: 'AddressUpdate'
} as const;

export const Body_login_login_access_tokenSchema = {
    properties: {
        grant_type: {
            anyOf: [
                {
                    type: 'string',
                    pattern: '^password$'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Grant Type'
        },
        username: {
            type: 'string',
            title: 'Username'
        },
        password: {
            type: 'string',
            format: 'password',
            title: 'Password'
        },
        scope: {
            type: 'string',
            title: 'Scope',
            default: ''
        },
        client_id: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Client Id'
        },
        client_secret: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            format: 'password',
            title: 'Client Secret'
        }
    },
    type: 'object',
    required: ['username', 'password'],
    title: 'Body_login-login_access_token'
} as const;

export const CartItemAddSchema = {
    properties: {
        dish_sku_id: {
            type: 'string',
            format: 'uuid',
            title: 'Dish Sku Id'
        },
        quantity: {
            type: 'integer',
            minimum: 1,
            title: 'Quantity',
            default: 1
        }
    },
    type: 'object',
    required: ['dish_sku_id'],
    title: 'CartItemAdd'
} as const;

export const CartItemPublicSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        dish_sku_id: {
            type: 'string',
            format: 'uuid',
            title: 'Dish Sku Id'
        },
        dish_name: {
            type: 'string',
            title: 'Dish Name'
        },
        sku_name: {
            type: 'string',
            title: 'Sku Name'
        },
        unit_price: {
            type: 'string',
            pattern: '^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$',
            title: 'Unit Price'
        },
        quantity: {
            type: 'integer',
            title: 'Quantity'
        },
        line_amount: {
            type: 'string',
            pattern: '^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$',
            title: 'Line Amount'
        },
        stock: {
            type: 'integer',
            title: 'Stock'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active'
        }
    },
    type: 'object',
    required: ['id', 'dish_sku_id', 'dish_name', 'sku_name', 'unit_price', 'quantity', 'line_amount', 'stock', 'is_active'],
    title: 'CartItemPublic'
} as const;

export const CartItemUpdateSchema = {
    properties: {
        quantity: {
            type: 'integer',
            minimum: 1,
            title: 'Quantity'
        }
    },
    type: 'object',
    required: ['quantity'],
    title: 'CartItemUpdate'
} as const;

export const CartOverviewSchema = {
    properties: {
        items_count: {
            type: 'integer',
            title: 'Items Count'
        },
        total_amount: {
            type: 'string',
            pattern: '^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$',
            title: 'Total Amount'
        }
    },
    type: 'object',
    required: ['items_count', 'total_amount'],
    title: 'CartOverview'
} as const;

export const CartPublicSchema = {
    properties: {
        items: {
            items: {
                '$ref': '#/components/schemas/CartItemPublic'
            },
            type: 'array',
            title: 'Items'
        },
        total_amount: {
            type: 'string',
            pattern: '^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$',
            title: 'Total Amount'
        }
    },
    type: 'object',
    required: ['items', 'total_amount'],
    title: 'CartPublic'
} as const;

export const CategoryCreateSchema = {
    properties: {
        name: {
            type: 'string',
            maxLength: 255,
            minLength: 1,
            title: 'Name'
        },
        sort_order: {
            type: 'integer',
            title: 'Sort Order',
            default: 0
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active',
            default: true
        }
    },
    type: 'object',
    required: ['name'],
    title: 'CategoryCreate'
} as const;

export const CategoryPublicSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        name: {
            type: 'string',
            title: 'Name'
        },
        sort_order: {
            type: 'integer',
            title: 'Sort Order'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active'
        },
        created_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Created At'
        }
    },
    type: 'object',
    required: ['id', 'name', 'sort_order', 'is_active'],
    title: 'CategoryPublic'
} as const;

export const CategoryUpdateSchema = {
    properties: {
        name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255,
                    minLength: 1
                },
                {
                    type: 'null'
                }
            ],
            title: 'Name'
        },
        sort_order: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Sort Order'
        },
        is_active: {
            anyOf: [
                {
                    type: 'boolean'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Is Active'
        }
    },
    type: 'object',
    title: 'CategoryUpdate'
} as const;

export const DashboardOverviewSchema = {
    properties: {
        scope: {
            type: 'string',
            title: 'Scope'
        },
        menu: {
            '$ref': '#/components/schemas/MenuOverview'
        },
        addresses: {
            '$ref': '#/components/schemas/AddressOverview'
        },
        cart: {
            '$ref': '#/components/schemas/CartOverview'
        },
        orders: {
            '$ref': '#/components/schemas/OrdersOverview'
        },
        payments: {
            '$ref': '#/components/schemas/PaymentsOverview'
        },
        recent_orders: {
            items: {
                '$ref': '#/components/schemas/RecentOrder'
            },
            type: 'array',
            title: 'Recent Orders'
        }
    },
    type: 'object',
    required: ['scope', 'menu', 'addresses', 'cart', 'orders', 'payments', 'recent_orders'],
    title: 'DashboardOverview'
} as const;

export const DishCreateSchema = {
    properties: {
        category_id: {
            type: 'string',
            format: 'uuid',
            title: 'Category Id'
        },
        name: {
            type: 'string',
            maxLength: 255,
            minLength: 1,
            title: 'Name'
        },
        description: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 1000
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active',
            default: true
        }
    },
    type: 'object',
    required: ['category_id', 'name'],
    title: 'DishCreate'
} as const;

export const DishPublicSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        category_id: {
            type: 'string',
            format: 'uuid',
            title: 'Category Id'
        },
        name: {
            type: 'string',
            title: 'Name'
        },
        description: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active'
        },
        created_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Created At'
        }
    },
    type: 'object',
    required: ['id', 'category_id', 'name', 'is_active'],
    title: 'DishPublic'
} as const;

export const DishSkuCreateSchema = {
    properties: {
        name: {
            type: 'string',
            maxLength: 255,
            minLength: 1,
            title: 'Name'
        },
        price: {
            anyOf: [
                {
                    type: 'number',
                    exclusiveMinimum: 0
                },
                {
                    type: 'string',
                    pattern: '^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$'
                }
            ],
            title: 'Price'
        },
        stock: {
            type: 'integer',
            minimum: 0,
            title: 'Stock',
            default: 0
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active',
            default: true
        }
    },
    type: 'object',
    required: ['name', 'price'],
    title: 'DishSkuCreate'
} as const;

export const DishSkuPublicSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        dish_id: {
            type: 'string',
            format: 'uuid',
            title: 'Dish Id'
        },
        name: {
            type: 'string',
            title: 'Name'
        },
        price: {
            type: 'string',
            pattern: '^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$',
            title: 'Price'
        },
        stock: {
            type: 'integer',
            title: 'Stock'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active'
        },
        created_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Created At'
        }
    },
    type: 'object',
    required: ['id', 'dish_id', 'name', 'price', 'stock', 'is_active'],
    title: 'DishSkuPublic'
} as const;

export const DishSkuUpdateSchema = {
    properties: {
        name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255,
                    minLength: 1
                },
                {
                    type: 'null'
                }
            ],
            title: 'Name'
        },
        price: {
            anyOf: [
                {
                    type: 'number',
                    exclusiveMinimum: 0
                },
                {
                    type: 'string',
                    pattern: '^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Price'
        },
        stock: {
            anyOf: [
                {
                    type: 'integer',
                    minimum: 0
                },
                {
                    type: 'null'
                }
            ],
            title: 'Stock'
        },
        is_active: {
            anyOf: [
                {
                    type: 'boolean'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Is Active'
        }
    },
    type: 'object',
    title: 'DishSkuUpdate'
} as const;

export const DishUpdateSchema = {
    properties: {
        category_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Category Id'
        },
        name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255,
                    minLength: 1
                },
                {
                    type: 'null'
                }
            ],
            title: 'Name'
        },
        description: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 1000
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        },
        is_active: {
            anyOf: [
                {
                    type: 'boolean'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Is Active'
        }
    },
    type: 'object',
    title: 'DishUpdate'
} as const;

export const HTTPValidationErrorSchema = {
    properties: {
        detail: {
            items: {
                '$ref': '#/components/schemas/ValidationError'
            },
            type: 'array',
            title: 'Detail'
        }
    },
    type: 'object',
    title: 'HTTPValidationError'
} as const;

export const ItemCreateSchema = {
    properties: {
        title: {
            type: 'string',
            maxLength: 255,
            minLength: 1,
            title: 'Title'
        },
        description: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        }
    },
    type: 'object',
    required: ['title'],
    title: 'ItemCreate'
} as const;

export const ItemPublicSchema = {
    properties: {
        title: {
            type: 'string',
            maxLength: 255,
            minLength: 1,
            title: 'Title'
        },
        description: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        owner_id: {
            type: 'string',
            format: 'uuid',
            title: 'Owner Id'
        },
        created_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Created At'
        }
    },
    type: 'object',
    required: ['title', 'id', 'owner_id'],
    title: 'ItemPublic'
} as const;

export const ItemUpdateSchema = {
    properties: {
        title: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255,
                    minLength: 1
                },
                {
                    type: 'null'
                }
            ],
            title: 'Title'
        },
        description: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        }
    },
    type: 'object',
    title: 'ItemUpdate'
} as const;

export const ItemsPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/ItemPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'ItemsPublic'
} as const;

export const MenuOverviewSchema = {
    properties: {
        categories_total: {
            type: 'integer',
            title: 'Categories Total'
        },
        categories_active: {
            type: 'integer',
            title: 'Categories Active'
        },
        dishes_total: {
            type: 'integer',
            title: 'Dishes Total'
        },
        dishes_active: {
            type: 'integer',
            title: 'Dishes Active'
        },
        skus_total: {
            type: 'integer',
            title: 'Skus Total'
        },
        skus_active: {
            type: 'integer',
            title: 'Skus Active'
        }
    },
    type: 'object',
    required: ['categories_total', 'categories_active', 'dishes_total', 'dishes_active', 'skus_total', 'skus_active'],
    title: 'MenuOverview'
} as const;

export const MessageSchema = {
    properties: {
        message: {
            type: 'string',
            title: 'Message'
        }
    },
    type: 'object',
    required: ['message'],
    title: 'Message'
} as const;

export const NewPasswordSchema = {
    properties: {
        token: {
            type: 'string',
            title: 'Token'
        },
        new_password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'New Password'
        }
    },
    type: 'object',
    required: ['token', 'new_password'],
    title: 'NewPassword'
} as const;

export const OrderCreateSchema = {
    properties: {
        address_id: {
            type: 'string',
            format: 'uuid',
            title: 'Address Id'
        }
    },
    type: 'object',
    required: ['address_id'],
    title: 'OrderCreate'
} as const;

export const OrderDetailPublicSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        user_id: {
            type: 'string',
            format: 'uuid',
            title: 'User Id'
        },
        address_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Address Id'
        },
        order_no: {
            type: 'string',
            title: 'Order No'
        },
        status: {
            '$ref': '#/components/schemas/OrderStatus'
        },
        total_amount: {
            type: 'string',
            pattern: '^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$',
            title: 'Total Amount'
        },
        paid_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Paid At'
        },
        created_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Created At'
        },
        items: {
            items: {
                '$ref': '#/components/schemas/OrderItemPublic'
            },
            type: 'array',
            title: 'Items'
        },
        status_logs: {
            items: {
                '$ref': '#/components/schemas/OrderStatusLogPublic'
            },
            type: 'array',
            title: 'Status Logs'
        }
    },
    type: 'object',
    required: ['id', 'user_id', 'address_id', 'order_no', 'status', 'total_amount', 'items', 'status_logs'],
    title: 'OrderDetailPublic'
} as const;

export const OrderItemPublicSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        dish_sku_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Dish Sku Id'
        },
        dish_name_snapshot: {
            type: 'string',
            title: 'Dish Name Snapshot'
        },
        sku_name_snapshot: {
            type: 'string',
            title: 'Sku Name Snapshot'
        },
        unit_price: {
            type: 'string',
            pattern: '^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$',
            title: 'Unit Price'
        },
        quantity: {
            type: 'integer',
            title: 'Quantity'
        },
        line_amount: {
            type: 'string',
            pattern: '^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$',
            title: 'Line Amount'
        }
    },
    type: 'object',
    required: ['id', 'dish_sku_id', 'dish_name_snapshot', 'sku_name_snapshot', 'unit_price', 'quantity', 'line_amount'],
    title: 'OrderItemPublic'
} as const;

export const OrderPublicSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        user_id: {
            type: 'string',
            format: 'uuid',
            title: 'User Id'
        },
        address_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Address Id'
        },
        order_no: {
            type: 'string',
            title: 'Order No'
        },
        status: {
            '$ref': '#/components/schemas/OrderStatus'
        },
        total_amount: {
            type: 'string',
            pattern: '^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$',
            title: 'Total Amount'
        },
        paid_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Paid At'
        },
        created_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Created At'
        }
    },
    type: 'object',
    required: ['id', 'user_id', 'address_id', 'order_no', 'status', 'total_amount'],
    title: 'OrderPublic'
} as const;

export const OrderStatusSchema = {
    type: 'string',
    enum: ['pending_payment', 'paid', 'accepted', 'preparing', 'ready_for_delivery', 'delivering', 'completed', 'cancelled', 'refund_pending', 'refunded', 'refund_rejected'],
    title: 'OrderStatus'
} as const;

export const OrderStatusChangeSchema = {
    properties: {
        event: {
            type: 'string',
            maxLength: 64,
            title: 'Event'
        },
        reason: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Reason'
        }
    },
    type: 'object',
    required: ['event'],
    title: 'OrderStatusChange'
} as const;

export const OrderStatusLogPublicSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        from_status: {
            anyOf: [
                {
                    '$ref': '#/components/schemas/OrderStatus'
                },
                {
                    type: 'null'
                }
            ]
        },
        to_status: {
            '$ref': '#/components/schemas/OrderStatus'
        },
        event: {
            type: 'string',
            title: 'Event'
        },
        actor: {
            type: 'string',
            title: 'Actor'
        },
        reason: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Reason'
        },
        created_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Created At'
        }
    },
    type: 'object',
    required: ['id', 'from_status', 'to_status', 'event', 'actor', 'reason'],
    title: 'OrderStatusLogPublic'
} as const;

export const OrdersOverviewSchema = {
    properties: {
        total: {
            type: 'integer',
            title: 'Total'
        },
        today: {
            type: 'integer',
            title: 'Today'
        },
        realized_gmv: {
            type: 'string',
            pattern: '^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$',
            title: 'Realized Gmv'
        },
        status_breakdown: {
            items: {
                '$ref': '#/components/schemas/StatusCount'
            },
            type: 'array',
            title: 'Status Breakdown'
        }
    },
    type: 'object',
    required: ['total', 'today', 'realized_gmv', 'status_breakdown'],
    title: 'OrdersOverview'
} as const;

export const PaymentCallbackSchema = {
    properties: {
        provider: {
            type: 'string',
            maxLength: 32,
            title: 'Provider'
        },
        transaction_id: {
            type: 'string',
            maxLength: 128,
            title: 'Transaction Id'
        },
        payload: {
            type: 'string',
            title: 'Payload'
        },
        signature: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Signature'
        }
    },
    type: 'object',
    required: ['provider', 'transaction_id', 'payload'],
    title: 'PaymentCallback'
} as const;

export const PaymentCreateSchema = {
    properties: {
        order_id: {
            type: 'string',
            format: 'uuid',
            title: 'Order Id'
        },
        provider: {
            type: 'string',
            maxLength: 32,
            title: 'Provider'
        }
    },
    type: 'object',
    required: ['order_id', 'provider'],
    title: 'PaymentCreate'
} as const;

export const PaymentCreatePublicSchema = {
    properties: {
        order_id: {
            type: 'string',
            format: 'uuid',
            title: 'Order Id'
        },
        provider: {
            type: 'string',
            title: 'Provider'
        },
        out_trade_no: {
            type: 'string',
            title: 'Out Trade No'
        },
        amount: {
            type: 'string',
            pattern: '^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$',
            title: 'Amount'
        },
        status: {
            '$ref': '#/components/schemas/PaymentStatus'
        }
    },
    type: 'object',
    required: ['order_id', 'provider', 'out_trade_no', 'amount', 'status'],
    title: 'PaymentCreatePublic'
} as const;

export const PaymentStatusSchema = {
    type: 'string',
    enum: ['pending', 'success', 'failed', 'refunded'],
    title: 'PaymentStatus'
} as const;

export const PaymentsOverviewSchema = {
    properties: {
        total: {
            type: 'integer',
            title: 'Total'
        },
        success_amount: {
            type: 'string',
            pattern: '^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$',
            title: 'Success Amount'
        },
        status_breakdown: {
            items: {
                '$ref': '#/components/schemas/StatusCount'
            },
            type: 'array',
            title: 'Status Breakdown'
        }
    },
    type: 'object',
    required: ['total', 'success_amount', 'status_breakdown'],
    title: 'PaymentsOverview'
} as const;

export const PrivateUserCreateSchema = {
    properties: {
        email: {
            type: 'string',
            title: 'Email'
        },
        password: {
            type: 'string',
            title: 'Password'
        },
        full_name: {
            type: 'string',
            title: 'Full Name'
        },
        is_verified: {
            type: 'boolean',
            title: 'Is Verified',
            default: false
        }
    },
    type: 'object',
    required: ['email', 'password', 'full_name'],
    title: 'PrivateUserCreate'
} as const;

export const RecentOrderSchema = {
    properties: {
        id: {
            type: 'string',
            title: 'Id'
        },
        order_no: {
            type: 'string',
            title: 'Order No'
        },
        status: {
            '$ref': '#/components/schemas/OrderStatus'
        },
        total_amount: {
            type: 'string',
            pattern: '^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$',
            title: 'Total Amount'
        },
        created_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Created At'
        }
    },
    type: 'object',
    required: ['id', 'order_no', 'status', 'total_amount'],
    title: 'RecentOrder'
} as const;

export const StatusCountSchema = {
    properties: {
        status: {
            type: 'string',
            title: 'Status'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['status', 'count'],
    title: 'StatusCount'
} as const;

export const TokenSchema = {
    properties: {
        access_token: {
            type: 'string',
            title: 'Access Token'
        },
        token_type: {
            type: 'string',
            title: 'Token Type',
            default: 'bearer'
        }
    },
    type: 'object',
    required: ['access_token'],
    title: 'Token'
} as const;

export const UpdatePasswordSchema = {
    properties: {
        current_password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'Current Password'
        },
        new_password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'New Password'
        }
    },
    type: 'object',
    required: ['current_password', 'new_password'],
    title: 'UpdatePassword'
} as const;

export const UserCreateSchema = {
    properties: {
        email: {
            type: 'string',
            maxLength: 255,
            format: 'email',
            title: 'Email'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active',
            default: true
        },
        is_superuser: {
            type: 'boolean',
            title: 'Is Superuser',
            default: false
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'Password'
        }
    },
    type: 'object',
    required: ['email', 'password'],
    title: 'UserCreate'
} as const;

export const UserPublicSchema = {
    properties: {
        email: {
            type: 'string',
            maxLength: 255,
            format: 'email',
            title: 'Email'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active',
            default: true
        },
        is_superuser: {
            type: 'boolean',
            title: 'Is Superuser',
            default: false
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        created_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Created At'
        }
    },
    type: 'object',
    required: ['email', 'id'],
    title: 'UserPublic'
} as const;

export const UserRegisterSchema = {
    properties: {
        email: {
            type: 'string',
            maxLength: 255,
            format: 'email',
            title: 'Email'
        },
        password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'Password'
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        }
    },
    type: 'object',
    required: ['email', 'password'],
    title: 'UserRegister'
} as const;

export const UserUpdateSchema = {
    properties: {
        email: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255,
                    format: 'email'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Email'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active',
            default: true
        },
        is_superuser: {
            type: 'boolean',
            title: 'Is Superuser',
            default: false
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        password: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 128,
                    minLength: 8
                },
                {
                    type: 'null'
                }
            ],
            title: 'Password'
        }
    },
    type: 'object',
    title: 'UserUpdate'
} as const;

export const UserUpdateMeSchema = {
    properties: {
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        email: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255,
                    format: 'email'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Email'
        }
    },
    type: 'object',
    title: 'UserUpdateMe'
} as const;

export const UsersPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/UserPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'UsersPublic'
} as const;

export const ValidationErrorSchema = {
    properties: {
        loc: {
            items: {
                anyOf: [
                    {
                        type: 'string'
                    },
                    {
                        type: 'integer'
                    }
                ]
            },
            type: 'array',
            title: 'Location'
        },
        msg: {
            type: 'string',
            title: 'Message'
        },
        type: {
            type: 'string',
            title: 'Error Type'
        },
        input: {
            title: 'Input'
        },
        ctx: {
            type: 'object',
            title: 'Context'
        }
    },
    type: 'object',
    required: ['loc', 'msg', 'type'],
    title: 'ValidationError'
} as const;