// This file is auto-generated by @hey-api/openapi-ts

import type { CancelablePromise } from './core/CancelablePromise';
import { OpenAPI } from './core/OpenAPI';
import { request as __request } from './core/request';
import type { AddressesReadAddressesResponse, AddressesCreateAddressData, AddressesCreateAddressResponse, AddressesUpdateAddressData, AddressesUpdateAddressResponse, AddressesDeleteAddressData, AddressesDeleteAddressResponse, CartReadCartResponse, CartAddCartItemData, CartAddCartItemResponse, CartClearCartResponse, CartUpdateCartItemData, CartUpdateCartItemResponse, CartDeleteCartItemData, CartDeleteCartItemResponse, ItemsReadItemsData, ItemsReadItemsResponse, ItemsCreateItemData, ItemsCreateItemResponse, ItemsReadItemData, ItemsReadItemResponse, ItemsUpdateItemData, ItemsUpdateItemResponse, ItemsDeleteItemData, ItemsDeleteItemResponse, LoginLoginAccessTokenData, LoginLoginAccessTokenResponse, LoginTestTokenResponse, LoginRecoverPasswordData, LoginRecoverPasswordResponse, LoginResetPasswordData, LoginResetPasswordResponse, LoginRecoverPasswordHtmlContentData, LoginRecoverPasswordHtmlContentResponse, MenuReadCategoriesData, MenuReadCategoriesResponse, MenuReadDishesData, MenuReadDishesResponse, MenuReadDishSkusData, MenuReadDishSkusResponse, MenuSyncMenuResponse, OrdersReadOrdersResponse, OrdersCreateOrderData, OrdersCreateOrderResponse, OrdersReadOrderData, OrdersReadOrderResponse, OrdersChangeOrderStatusData, OrdersChangeOrderStatusResponse, PaymentsCreatePaymentData, PaymentsCreatePaymentResponse, PaymentsPaymentCallbackData, PaymentsPaymentCallbackResponse, PrivateCreateUserData, PrivateCreateUserResponse, UsersReadUsersData, UsersReadUsersResponse, UsersCreateUserData, UsersCreateUserResponse, UsersReadUserMeResponse, UsersDeleteUserMeResponse, UsersUpdateUserMeData, UsersUpdateUserMeResponse, UsersUpdatePasswordMeData, UsersUpdatePasswordMeResponse, UsersRegisterUserData, UsersRegisterUserResponse, UsersReadUserByIdData, UsersReadUserByIdResponse, UsersUpdateUserData, UsersUpdateUserResponse, UsersDeleteUserData, UsersDeleteUserResponse, UtilsTestEmailData, UtilsTestEmailResponse, UtilsHealthCheckResponse } from './types.gen';

export class AddressesService {
    /**
     * Read Addresses
     * Retrieve address list (skeleton).
     * @returns unknown Successful Response
     * @throws ApiError
     */
    public static readAddresses(): CancelablePromise<AddressesReadAddressesResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/addresses/'
        });
    }
    
    /**
     * Create Address
     * Create a new address (skeleton).
     * @param data The data for the request.
     * @param data.requestBody
     * @returns Message Successful Response
     * @throws ApiError
     */
    public static createAddress(data: AddressesCreateAddressData): CancelablePromise<AddressesCreateAddressResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/addresses/',
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Update Address
     * Update address (skeleton).
     * @param data The data for the request.
     * @param data.addressId
     * @param data.requestBody
     * @returns Message Successful Response
     * @throws ApiError
     */
    public static updateAddress(data: AddressesUpdateAddressData): CancelablePromise<AddressesUpdateAddressResponse> {
        return __request(OpenAPI, {
            method: 'PATCH',
            url: '/api/v1/addresses/{address_id}',
            path: {
                address_id: data.addressId
            },
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Delete Address
     * Delete address (skeleton).
     * @param data The data for the request.
     * @param data.addressId
     * @returns Message Successful Response
     * @throws ApiError
     */
    public static deleteAddress(data: AddressesDeleteAddressData): CancelablePromise<AddressesDeleteAddressResponse> {
        return __request(OpenAPI, {
            method: 'DELETE',
            url: '/api/v1/addresses/{address_id}',
            path: {
                address_id: data.addressId
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
}

export class CartService {
    /**
     * Read Cart
     * Retrieve current user's cart (skeleton).
     * @returns unknown Successful Response
     * @throws ApiError
     */
    public static readCart(): CancelablePromise<CartReadCartResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/cart/'
        });
    }
    
    /**
     * Add Cart Item
     * Add an item to cart (skeleton).
     * @param data The data for the request.
     * @param data.requestBody
     * @returns Message Successful Response
     * @throws ApiError
     */
    public static addCartItem(data: CartAddCartItemData): CancelablePromise<CartAddCartItemResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/cart/items',
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Clear Cart
     * Clear all cart items (skeleton).
     * @returns Message Successful Response
     * @throws ApiError
     */
    public static clearCart(): CancelablePromise<CartClearCartResponse> {
        return __request(OpenAPI, {
            method: 'DELETE',
            url: '/api/v1/cart/items'
        });
    }
    
    /**
     * Update Cart Item
     * Update cart item quantity (skeleton).
     * @param data The data for the request.
     * @param data.cartItemId
     * @param data.requestBody
     * @returns Message Successful Response
     * @throws ApiError
     */
    public static updateCartItem(data: CartUpdateCartItemData): CancelablePromise<CartUpdateCartItemResponse> {
        return __request(OpenAPI, {
            method: 'PATCH',
            url: '/api/v1/cart/items/{cart_item_id}',
            path: {
                cart_item_id: data.cartItemId
            },
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Delete Cart Item
     * Delete a cart item (skeleton).
     * @param data The data for the request.
     * @param data.cartItemId
     * @returns Message Successful Response
     * @throws ApiError
     */
    public static deleteCartItem(data: CartDeleteCartItemData): CancelablePromise<CartDeleteCartItemResponse> {
        return __request(OpenAPI, {
            method: 'DELETE',
            url: '/api/v1/cart/items/{cart_item_id}',
            path: {
                cart_item_id: data.cartItemId
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
}

export class ItemsService {
    /**
     * Read Items
     * Retrieve items.
     * @param data The data for the request.
     * @param data.skip
     * @param data.limit
     * @returns ItemsPublic Successful Response
     * @throws ApiError
     */
    public static readItems(data: ItemsReadItemsData = {}): CancelablePromise<ItemsReadItemsResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/items/',
            query: {
                skip: data.skip,
                limit: data.limit
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Create Item
     * Create new item.
     * @param data The data for the request.
     * @param data.requestBody
     * @returns ItemPublic Successful Response
     * @throws ApiError
     */
    public static createItem(data: ItemsCreateItemData): CancelablePromise<ItemsCreateItemResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/items/',
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Read Item
     * Get item by ID.
     * @param data The data for the request.
     * @param data.id
     * @returns ItemPublic Successful Response
     * @throws ApiError
     */
    public static readItem(data: ItemsReadItemData): CancelablePromise<ItemsReadItemResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/items/{id}',
            path: {
                id: data.id
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Update Item
     * Update an item.
     * @param data The data for the request.
     * @param data.id
     * @param data.requestBody
     * @returns ItemPublic Successful Response
     * @throws ApiError
     */
    public static updateItem(data: ItemsUpdateItemData): CancelablePromise<ItemsUpdateItemResponse> {
        return __request(OpenAPI, {
            method: 'PUT',
            url: '/api/v1/items/{id}',
            path: {
                id: data.id
            },
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Delete Item
     * Delete an item.
     * @param data The data for the request.
     * @param data.id
     * @returns Message Successful Response
     * @throws ApiError
     */
    public static deleteItem(data: ItemsDeleteItemData): CancelablePromise<ItemsDeleteItemResponse> {
        return __request(OpenAPI, {
            method: 'DELETE',
            url: '/api/v1/items/{id}',
            path: {
                id: data.id
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
}

export class LoginService {
    /**
     * Login Access Token
     * OAuth2 compatible token login, get an access token for future requests
     * @param data The data for the request.
     * @param data.formData
     * @returns Token Successful Response
     * @throws ApiError
     */
    public static loginAccessToken(data: LoginLoginAccessTokenData): CancelablePromise<LoginLoginAccessTokenResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/login/access-token',
            formData: data.formData,
            mediaType: 'application/x-www-form-urlencoded',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Test Token
     * Test access token
     * @returns UserPublic Successful Response
     * @throws ApiError
     */
    public static testToken(): CancelablePromise<LoginTestTokenResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/login/test-token'
        });
    }
    
    /**
     * Recover Password
     * Password Recovery
     * @param data The data for the request.
     * @param data.email
     * @returns Message Successful Response
     * @throws ApiError
     */
    public static recoverPassword(data: LoginRecoverPasswordData): CancelablePromise<LoginRecoverPasswordResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/password-recovery/{email}',
            path: {
                email: data.email
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Reset Password
     * Reset password
     * @param data The data for the request.
     * @param data.requestBody
     * @returns Message Successful Response
     * @throws ApiError
     */
    public static resetPassword(data: LoginResetPasswordData): CancelablePromise<LoginResetPasswordResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/reset-password/',
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Recover Password Html Content
     * HTML Content for Password Recovery
     * @param data The data for the request.
     * @param data.email
     * @returns string Successful Response
     * @throws ApiError
     */
    public static recoverPasswordHtmlContent(data: LoginRecoverPasswordHtmlContentData): CancelablePromise<LoginRecoverPasswordHtmlContentResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/password-recovery-html-content/{email}',
            path: {
                email: data.email
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
}

export class MenuService {
    /**
     * Read Categories
     * Retrieve menu categories (skeleton).
     * @param data The data for the request.
     * @param data.isActive
     * @returns unknown Successful Response
     * @throws ApiError
     */
    public static readCategories(data: MenuReadCategoriesData = {}): CancelablePromise<MenuReadCategoriesResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/menu/categories',
            query: {
                is_active: data.isActive
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Read Dishes
     * Retrieve dishes (skeleton).
     * @param data The data for the request.
     * @param data.categoryId
     * @param data.isActive
     * @returns unknown Successful Response
     * @throws ApiError
     */
    public static readDishes(data: MenuReadDishesData = {}): CancelablePromise<MenuReadDishesResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/menu/dishes',
            query: {
                category_id: data.categoryId,
                is_active: data.isActive
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Read Dish Skus
     * Retrieve SKU list for a dish (skeleton).
     * @param data The data for the request.
     * @param data.dishId
     * @returns unknown Successful Response
     * @throws ApiError
     */
    public static readDishSkus(data: MenuReadDishSkusData): CancelablePromise<MenuReadDishSkusResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/menu/dishes/{dish_id}/skus',
            path: {
                dish_id: data.dishId
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Sync Menu
     * Reserved endpoint for menu sync jobs (skeleton).
     * @returns Message Successful Response
     * @throws ApiError
     */
    public static syncMenu(): CancelablePromise<MenuSyncMenuResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/menu/sync'
        });
    }
}

export class OrdersService {
    /**
     * Read Orders
     * Retrieve order list (skeleton).
     * @returns unknown Successful Response
     * @throws ApiError
     */
    public static readOrders(): CancelablePromise<OrdersReadOrdersResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/orders/'
        });
    }
    
    /**
     * Create Order
     * Create order from cart (skeleton).
     * @param data The data for the request.
     * @param data.requestBody
     * @returns Message Successful Response
     * @throws ApiError
     */
    public static createOrder(data: OrdersCreateOrderData): CancelablePromise<OrdersCreateOrderResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/orders/',
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Read Order
     * Retrieve order detail (skeleton).
     * @param data The data for the request.
     * @param data.orderId
     * @returns unknown Successful Response
     * @throws ApiError
     */
    public static readOrder(data: OrdersReadOrderData): CancelablePromise<OrdersReadOrderResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/orders/{order_id}',
            path: {
                order_id: data.orderId
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Change Order Status
     * Change order status by event (skeleton).
     * @param data The data for the request.
     * @param data.orderId
     * @param data.requestBody
     * @returns Message Successful Response
     * @throws ApiError
     */
    public static changeOrderStatus(data: OrdersChangeOrderStatusData): CancelablePromise<OrdersChangeOrderStatusResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/orders/{order_id}/status',
            path: {
                order_id: data.orderId
            },
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
}

export class PaymentsService {
    /**
     * Create Payment
     * Create payment request (skeleton).
     * @param data The data for the request.
     * @param data.requestBody
     * @returns Message Successful Response
     * @throws ApiError
     */
    public static createPayment(data: PaymentsCreatePaymentData): CancelablePromise<PaymentsCreatePaymentResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/payments/create',
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Payment Callback
     * Handle payment callback (skeleton).
     * @param data The data for the request.
     * @param data.requestBody
     * @returns Message Successful Response
     * @throws ApiError
     */
    public static paymentCallback(data: PaymentsPaymentCallbackData): CancelablePromise<PaymentsPaymentCallbackResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/payments/callbacks',
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
}

export class PrivateService {
    /**
     * Create User
     * Create a new user.
     * @param data The data for the request.
     * @param data.requestBody
     * @returns UserPublic Successful Response
     * @throws ApiError
     */
    public static createUser(data: PrivateCreateUserData): CancelablePromise<PrivateCreateUserResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/private/users/',
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
}

export class UsersService {
    /**
     * Read Users
     * Retrieve users.
     * @param data The data for the request.
     * @param data.skip
     * @param data.limit
     * @returns UsersPublic Successful Response
     * @throws ApiError
     */
    public static readUsers(data: UsersReadUsersData = {}): CancelablePromise<UsersReadUsersResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/users/',
            query: {
                skip: data.skip,
                limit: data.limit
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Create User
     * Create new user.
     * @param data The data for the request.
     * @param data.requestBody
     * @returns UserPublic Successful Response
     * @throws ApiError
     */
    public static createUser(data: UsersCreateUserData): CancelablePromise<UsersCreateUserResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/users/',
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Read User Me
     * Get current user.
     * @returns UserPublic Successful Response
     * @throws ApiError
     */
    public static readUserMe(): CancelablePromise<UsersReadUserMeResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/users/me'
        });
    }
    
    /**
     * Delete User Me
     * Delete own user.
     * @returns Message Successful Response
     * @throws ApiError
     */
    public static deleteUserMe(): CancelablePromise<UsersDeleteUserMeResponse> {
        return __request(OpenAPI, {
            method: 'DELETE',
            url: '/api/v1/users/me'
        });
    }
    
    /**
     * Update User Me
     * Update own user.
     * @param data The data for the request.
     * @param data.requestBody
     * @returns UserPublic Successful Response
     * @throws ApiError
     */
    public static updateUserMe(data: UsersUpdateUserMeData): CancelablePromise<UsersUpdateUserMeResponse> {
        return __request(OpenAPI, {
            method: 'PATCH',
            url: '/api/v1/users/me',
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Update Password Me
     * Update own password.
     * @param data The data for the request.
     * @param data.requestBody
     * @returns Message Successful Response
     * @throws ApiError
     */
    public static updatePasswordMe(data: UsersUpdatePasswordMeData): CancelablePromise<UsersUpdatePasswordMeResponse> {
        return __request(OpenAPI, {
            method: 'PATCH',
            url: '/api/v1/users/me/password',
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Register User
     * Create new user without the need to be logged in.
     * @param data The data for the request.
     * @param data.requestBody
     * @returns UserPublic Successful Response
     * @throws ApiError
     */
    public static registerUser(data: UsersRegisterUserData): CancelablePromise<UsersRegisterUserResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/users/signup',
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Read User By Id
     * Get a specific user by id.
     * @param data The data for the request.
     * @param data.userId
     * @returns UserPublic Successful Response
     * @throws ApiError
     */
    public static readUserById(data: UsersReadUserByIdData): CancelablePromise<UsersReadUserByIdResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/users/{user_id}',
            path: {
                user_id: data.userId
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Update User
     * Update a user.
     * @param data The data for the request.
     * @param data.userId
     * @param data.requestBody
     * @returns UserPublic Successful Response
     * @throws ApiError
     */
    public static updateUser(data: UsersUpdateUserData): CancelablePromise<UsersUpdateUserResponse> {
        return __request(OpenAPI, {
            method: 'PATCH',
            url: '/api/v1/users/{user_id}',
            path: {
                user_id: data.userId
            },
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Delete User
     * Delete a user.
     * @param data The data for the request.
     * @param data.userId
     * @returns Message Successful Response
     * @throws ApiError
     */
    public static deleteUser(data: UsersDeleteUserData): CancelablePromise<UsersDeleteUserResponse> {
        return __request(OpenAPI, {
            method: 'DELETE',
            url: '/api/v1/users/{user_id}',
            path: {
                user_id: data.userId
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
}

export class UtilsService {
    /**
     * Test Email
     * Test emails.
     * @param data The data for the request.
     * @param data.emailTo
     * @returns Message Successful Response
     * @throws ApiError
     */
    public static testEmail(data: UtilsTestEmailData): CancelablePromise<UtilsTestEmailResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/utils/test-email/',
            query: {
                email_to: data.emailTo
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Health Check
     * @returns boolean Successful Response
     * @throws ApiError
     */
    public static healthCheck(): CancelablePromise<UtilsHealthCheckResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/utils/health-check/'
        });
    }
}