// This file is auto-generated by @hey-api/openapi-ts

export type AddressCreate = {
    receiver_name: string;
    receiver_phone: string;
    province: string;
    city: string;
    district: string;
    detail: string;
    is_default?: boolean;
};

export type AddressPublic = {
    id: string;
    user_id: string;
    receiver_name: string;
    receiver_phone: string;
    province: string;
    city: string;
    district: string;
    detail: string;
    is_default: boolean;
    created_at?: (string | null);
};

export type AddressUpdate = {
    receiver_name?: (string | null);
    receiver_phone?: (string | null);
    province?: (string | null);
    city?: (string | null);
    district?: (string | null);
    detail?: (string | null);
    is_default?: (boolean | null);
};

export type Body_login_login_access_token = {
    grant_type?: (string | null);
    username: string;
    password: string;
    scope?: string;
    client_id?: (string | null);
    client_secret?: (string | null);
};

export type CartItemAdd = {
    dish_sku_id: string;
    quantity?: number;
};

export type CartItemPublic = {
    id: string;
    dish_sku_id: string;
    dish_name: string;
    sku_name: string;
    unit_price: string;
    quantity: number;
    line_amount: string;
    stock: number;
    is_active: boolean;
};

export type CartItemUpdate = {
    quantity: number;
};

export type CartPublic = {
    items: Array<CartItemPublic>;
    total_amount: string;
};

export type CategoryCreate = {
    name: string;
    sort_order?: number;
    is_active?: boolean;
};

export type CategoryPublic = {
    id: string;
    name: string;
    sort_order: number;
    is_active: boolean;
    created_at?: (string | null);
};

export type CategoryUpdate = {
    name?: (string | null);
    sort_order?: (number | null);
    is_active?: (boolean | null);
};

export type DishCreate = {
    category_id: string;
    name: string;
    description?: (string | null);
    is_active?: boolean;
};

export type DishPublic = {
    id: string;
    category_id: string;
    name: string;
    description?: (string | null);
    is_active: boolean;
    created_at?: (string | null);
};

export type DishSkuCreate = {
    name: string;
    price: (number | string);
    stock?: number;
    is_active?: boolean;
};

export type DishSkuPublic = {
    id: string;
    dish_id: string;
    name: string;
    price: string;
    stock: number;
    is_active: boolean;
    created_at?: (string | null);
};

export type DishSkuUpdate = {
    name?: (string | null);
    price?: (number | string | null);
    stock?: (number | null);
    is_active?: (boolean | null);
};

export type DishUpdate = {
    category_id?: (string | null);
    name?: (string | null);
    description?: (string | null);
    is_active?: (boolean | null);
};

export type HTTPValidationError = {
    detail?: Array<ValidationError>;
};

export type ItemCreate = {
    title: string;
    description?: (string | null);
};

export type ItemPublic = {
    title: string;
    description?: (string | null);
    id: string;
    owner_id: string;
    created_at?: (string | null);
};

export type ItemsPublic = {
    data: Array<ItemPublic>;
    count: number;
};

export type ItemUpdate = {
    title?: (string | null);
    description?: (string | null);
};

export type Message = {
    message: string;
};

export type NewPassword = {
    token: string;
    new_password: string;
};

export type OrderCreate = {
    address_id: string;
};

export type OrderDetailPublic = {
    id: string;
    user_id: string;
    address_id: (string | null);
    order_no: string;
    status: OrderStatus;
    total_amount: string;
    paid_at?: (string | null);
    created_at?: (string | null);
    items: Array<OrderItemPublic>;
    status_logs: Array<OrderStatusLogPublic>;
};

export type OrderItemPublic = {
    id: string;
    dish_sku_id: (string | null);
    dish_name_snapshot: string;
    sku_name_snapshot: string;
    unit_price: string;
    quantity: number;
    line_amount: string;
};

export type OrderPublic = {
    id: string;
    user_id: string;
    address_id: (string | null);
    order_no: string;
    status: OrderStatus;
    total_amount: string;
    paid_at?: (string | null);
    created_at?: (string | null);
};

export type OrderStatus = 'pending_payment' | 'paid' | 'accepted' | 'preparing' | 'ready_for_delivery' | 'delivering' | 'completed' | 'cancelled' | 'refund_pending' | 'refunded' | 'refund_rejected';

export type OrderStatusChange = {
    event: string;
    reason?: (string | null);
};

export type OrderStatusLogPublic = {
    id: string;
    from_status: (OrderStatus | null);
    to_status: OrderStatus;
    event: string;
    actor: string;
    reason: (string | null);
    created_at?: (string | null);
};

export type PaymentCallback = {
    provider: string;
    transaction_id: string;
    payload: string;
    signature?: (string | null);
};

export type PaymentCreate = {
    order_id: string;
    provider: string;
};

export type PaymentCreatePublic = {
    order_id: string;
    provider: string;
    out_trade_no: string;
    amount: string;
    status: PaymentStatus;
};

export type PaymentStatus = 'pending' | 'success' | 'failed' | 'refunded';

export type PrivateUserCreate = {
    email: string;
    password: string;
    full_name: string;
    is_verified?: boolean;
};

export type Token = {
    access_token: string;
    token_type?: string;
};

export type UpdatePassword = {
    current_password: string;
    new_password: string;
};

export type UserCreate = {
    email: string;
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    password: string;
};

export type UserPublic = {
    email: string;
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    id: string;
    created_at?: (string | null);
};

export type UserRegister = {
    email: string;
    password: string;
    full_name?: (string | null);
};

export type UsersPublic = {
    data: Array<UserPublic>;
    count: number;
};

export type UserUpdate = {
    email?: (string | null);
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    password?: (string | null);
};

export type UserUpdateMe = {
    full_name?: (string | null);
    email?: (string | null);
};

export type ValidationError = {
    loc: Array<(string | number)>;
    msg: string;
    type: string;
    input?: unknown;
    ctx?: {
        [key: string]: unknown;
    };
};

export type AddressesReadAddressesResponse = (Array<AddressPublic>);

export type AddressesCreateAddressData = {
    requestBody: AddressCreate;
};

export type AddressesCreateAddressResponse = (AddressPublic);

export type AddressesUpdateAddressData = {
    addressId: string;
    requestBody: AddressUpdate;
};

export type AddressesUpdateAddressResponse = (AddressPublic);

export type AddressesDeleteAddressData = {
    addressId: string;
};

export type AddressesDeleteAddressResponse = (Message);

export type CartReadCartResponse = (CartPublic);

export type CartAddCartItemData = {
    requestBody: CartItemAdd;
};

export type CartAddCartItemResponse = (Message);

export type CartClearCartResponse = (Message);

export type CartUpdateCartItemData = {
    cartItemId: string;
    requestBody: CartItemUpdate;
};

export type CartUpdateCartItemResponse = (Message);

export type CartDeleteCartItemData = {
    cartItemId: string;
};

export type CartDeleteCartItemResponse = (Message);

export type ItemsReadItemsData = {
    limit?: number;
    skip?: number;
};

export type ItemsReadItemsResponse = (ItemsPublic);

export type ItemsCreateItemData = {
    requestBody: ItemCreate;
};

export type ItemsCreateItemResponse = (ItemPublic);

export type ItemsReadItemData = {
    id: string;
};

export type ItemsReadItemResponse = (ItemPublic);

export type ItemsUpdateItemData = {
    id: string;
    requestBody: ItemUpdate;
};

export type ItemsUpdateItemResponse = (ItemPublic);

export type ItemsDeleteItemData = {
    id: string;
};

export type ItemsDeleteItemResponse = (Message);

export type LoginLoginAccessTokenData = {
    formData: Body_login_login_access_token;
};

export type LoginLoginAccessTokenResponse = (Token);

export type LoginTestTokenResponse = (UserPublic);

export type LoginRecoverPasswordData = {
    email: string;
};

export type LoginRecoverPasswordResponse = (Message);

export type LoginResetPasswordData = {
    requestBody: NewPassword;
};

export type LoginResetPasswordResponse = (Message);

export type LoginRecoverPasswordHtmlContentData = {
    email: string;
};

export type LoginRecoverPasswordHtmlContentResponse = (string);

export type MenuReadCategoriesData = {
    isActive?: (boolean | null);
};

export type MenuReadCategoriesResponse = (Array<CategoryPublic>);

export type MenuCreateCategoryData = {
    requestBody: CategoryCreate;
};

export type MenuCreateCategoryResponse = (CategoryPublic);

export type MenuUpdateCategoryData = {
    categoryId: string;
    requestBody: CategoryUpdate;
};

export type MenuUpdateCategoryResponse = (CategoryPublic);

export type MenuDeleteCategoryData = {
    categoryId: string;
};

export type MenuDeleteCategoryResponse = (Message);

export type MenuReadDishesData = {
    categoryId?: (string | null);
    isActive?: (boolean | null);
    limit?: number;
    skip?: number;
};

export type MenuReadDishesResponse = (Array<DishPublic>);

export type MenuCreateDishData = {
    requestBody: DishCreate;
};

export type MenuCreateDishResponse = (DishPublic);

export type MenuUpdateDishData = {
    dishId: string;
    requestBody: DishUpdate;
};

export type MenuUpdateDishResponse = (DishPublic);

export type MenuDeleteDishData = {
    dishId: string;
};

export type MenuDeleteDishResponse = (Message);

export type MenuReadDishSkusData = {
    dishId: string;
    isActive?: (boolean | null);
};

export type MenuReadDishSkusResponse = (Array<DishSkuPublic>);

export type MenuCreateDishSkuData = {
    dishId: string;
    requestBody: DishSkuCreate;
};

export type MenuCreateDishSkuResponse = (DishSkuPublic);

export type MenuUpdateDishSkuData = {
    requestBody: DishSkuUpdate;
    skuId: string;
};

export type MenuUpdateDishSkuResponse = (DishSkuPublic);

export type MenuDeleteDishSkuData = {
    skuId: string;
};

export type MenuDeleteDishSkuResponse = (Message);

export type OrdersReadOrdersData = {
    status?: (OrderStatus | null);
};

export type OrdersReadOrdersResponse = (Array<OrderPublic>);

export type OrdersCreateOrderData = {
    requestBody: OrderCreate;
};

export type OrdersCreateOrderResponse = (OrderDetailPublic);

export type OrdersReadOrderData = {
    orderId: string;
};

export type OrdersReadOrderResponse = (OrderDetailPublic);

export type OrdersChangeOrderStatusData = {
    orderId: string;
    requestBody: OrderStatusChange;
};

export type OrdersChangeOrderStatusResponse = (OrderDetailPublic);

export type PaymentsCreatePaymentData = {
    requestBody: PaymentCreate;
};

export type PaymentsCreatePaymentResponse = (PaymentCreatePublic);

export type PaymentsPaymentCallbackData = {
    requestBody: PaymentCallback;
};

export type PaymentsPaymentCallbackResponse = (PaymentCreatePublic);

export type PrivateCreateUserData = {
    requestBody: PrivateUserCreate;
};

export type PrivateCreateUserResponse = (UserPublic);

export type UsersReadUsersData = {
    limit?: number;
    skip?: number;
};

export type UsersReadUsersResponse = (UsersPublic);

export type UsersCreateUserData = {
    requestBody: UserCreate;
};

export type UsersCreateUserResponse = (UserPublic);

export type UsersReadUserMeResponse = (UserPublic);

export type UsersDeleteUserMeResponse = (Message);

export type UsersUpdateUserMeData = {
    requestBody: UserUpdateMe;
};

export type UsersUpdateUserMeResponse = (UserPublic);

export type UsersUpdatePasswordMeData = {
    requestBody: UpdatePassword;
};

export type UsersUpdatePasswordMeResponse = (Message);

export type UsersRegisterUserData = {
    requestBody: UserRegister;
};

export type UsersRegisterUserResponse = (UserPublic);

export type UsersReadUserByIdData = {
    userId: string;
};

export type UsersReadUserByIdResponse = (UserPublic);

export type UsersUpdateUserData = {
    requestBody: UserUpdate;
    userId: string;
};

export type UsersUpdateUserResponse = (UserPublic);

export type UsersDeleteUserData = {
    userId: string;
};

export type UsersDeleteUserResponse = (Message);

export type UtilsTestEmailData = {
    emailTo: string;
};

export type UtilsTestEmailResponse = (Message);

export type UtilsHealthCheckResponse = (boolean);